/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// V4MessagesBodyAttachments struct for V4MessagesBodyAttachments
type V4MessagesBodyAttachments struct {
	// MIME version. By default set to `1.0`
	Version string `json:"version,omitempty"`
	// MIME type. By default set to `application/octet-stream`
	Type string `json:"type,omitempty"`
	// Content-disposition, either `inline` or `attachment`. By default set to `attachment`
	Disposition string `json:"disposition,omitempty"`
	// Name of attached file
	Filename string `json:"filename,omitempty"`
	// Content ID for inline dispositions. By default this is equal to the filename. Can be used in HTML content to address an attached image using “cid:” URL scheme.
	Cid string `json:"cid,omitempty"`
	// Actual attachment content in its raw form
	Content string `json:"content,omitempty"`
}
