/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// GetCallbackDetails struct for GetCallbackDetails
type GetCallbackDetails struct {
	// Request status.
	Status string                 `json:"status,omitempty"`
	Data   GetCallbackDetailsData `json:"data,omitempty"`
}
