/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// V4MessagesOriginator At least one of `from` or `reply_to` must be specified here.
type V4MessagesOriginator struct {
	From    *V4MessagesRecipientsTo `json:"from,omitempty"`
	ReplyTo *V4MessagesRecipientsTo `json:"reply_to,omitempty"`
}
