/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// V4MessagesRecipientsTo Full Email Address object
type V4MessagesRecipientsTo struct {
	// Name of a person, must be a valid RFC 2822 name
	Name string `json:"name,omitempty"`
	// Email address, as specified in RFC 2822
	Address string `json:"address,omitempty"`
}
