/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// MessagesResponseDataDetailsDelivery struct for MessagesResponseDataDetailsDelivery
type MessagesResponseDataDetailsDelivery struct {
	// Timestamp of when the message was delivered
	Finished string `json:"finished,omitempty"`
	// Number of retries after the initial delivery attempt
	Retries int32 `json:"retries,omitempty"`
	// One of:    * delivered   * failed   * queued
	Event string `json:"event,omitempty"`
	// The last SMTP response code received from a peer
	Code string `json:"code,omitempty"`
	// The last SMTP response message received from a peer
	Status string `json:"status,omitempty"`
}
