/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// StatsResponseData Stats data.
type StatsResponseData struct {
	Items []StatsResponseDataItems `json:"items,omitempty"`
}
