/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// StatusResponse struct for StatusResponse
type StatusResponse struct {
	// Request status.
	Status string `json:"status,omitempty"`
	// empty object
	Data map[string]interface{} `json:"data,omitempty"`
}
