/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// ReportsDataOndemand struct for ReportsDataOndemand
type ReportsDataOndemand struct {
	// Current status of a given on-demand report
	Status string `json:"status,omitempty"`
	// Human readable name of an on-demand report (auto-generated)
	Name string `json:"name,omitempty"`
	// The unique URL from which to download an on-demand report
	Url string `json:"url,omitempty"`
	// Time when a given on-demand report has been requestedi. RFC 2822 or UNIX epoch format
	TimeReq int32 `json:"time_req,omitempty"`
	// Percentage of completion for an on-demand report
	Progress int32 `json:"progress,omitempty"`
	// Name of the channel for which a given report has been defined
	Channel string `json:"channel,omitempty"`
	// Unique report ID
	ReportId string `json:"report_id,omitempty"`
}
