/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// CreateDkimKeyData Domains
type CreateDkimKeyData struct {
	// request result
	DkimKey string `json:"dkim_key,omitempty"`
}
