/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// MessagesResponseDataOpensItems struct for MessagesResponseDataOpensItems
type MessagesResponseDataOpensItems struct {
	// Timestamp of when the message was opened
	OpenTime string `json:"open_time,omitempty"`
	// IP address of where the message was opened
	RemoteIp string `json:"remote_ip,omitempty"`
	// User agent of device on which the message was opened
	Ua string `json:"ua,omitempty"`
}
