/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// PostMessageResponseData struct for PostMessageResponseData
type PostMessageResponseData struct {
	// Unique Message ID of accepted message
	MsgId string `json:"msg_id,omitempty"`
}
