/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// MessagesResponseDataAbuseComplaints struct for MessagesResponseDataAbuseComplaints
type MessagesResponseDataAbuseComplaints struct {
	// Time when the complaint was made
	ReportTime string `json:"report_time,omitempty"`
	// Abuse provider information
	Provider string `json:"provider,omitempty"`
}
