/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// ReportsDataPeriodic struct for ReportsDataPeriodic
type ReportsDataPeriodic struct {
	// Periodic report frequency
	Frequency string `json:"frequency,omitempty"`
	// Unique report ID
	ReportId string `json:"report_id,omitempty"`
	// Preset of events returned in a periodic report
	Events string `json:"events,omitempty"`
	// Name of the channel for which a given report has been defined
	Channel string `json:"channel,omitempty"`
	// The hour at which the report should be sent, values range from 0 to 23
	ReportTime string `json:"report_time,omitempty"`
}
