/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// InlineObject struct for InlineObject
type InlineObject struct {
	// Name of  the channel through which the email will be sent
	Channel    string               `json:"channel,omitempty"`
	Recipients V4MessagesRecipients `json:"recipients,omitempty"`
	Originator V4MessagesOriginator `json:"originator,omitempty"`
	// A name of a header to customize (both standard and non-standard) and its value, which can be either string or array of strings
	CustomHeaders map[string]interface{} `json:"custom_headers,omitempty"`
	// Email subject. Multiline value is supported, `998` characters max
	Subject string         `json:"subject,omitempty"`
	Body    V4MessagesBody `json:"body,omitempty"`
}
