/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	// A completely prepared full MIME container of the email, compliant with RFC 2045, RFC 2046, RFC 2047, RFC 4288, RFC 4289 and RFC 2049. No validation will be performed during API submission and it will be attempted to be delivered as is. Any errors while processing and delivering this email will be available only via callbacks.
	Mime string `json:"mime,omitempty"`
	// Name of the channel through which the email will be sent.
	Channel    string                   `json:"channel,omitempty"`
	Recipients V4MessagesMimeRecipients `json:"recipients,omitempty"`
	Originator V4MessagesOriginator     `json:"originator,omitempty"`
}
