/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// ChannelsDataItems struct for ChannelsDataItems
type ChannelsDataItems struct {
	// Current status of the channel
	Status string `json:"status,omitempty"`
	// Quota for the channel
	Quota int32 `json:"quota,omitempty"`
	// Name of the channel (sender)
	Name string `json:"name,omitempty"`
	// Current usage for the channel
	Usage int32 `json:"usage,omitempty"`
	// Timestamp for when the channel was originally created
	DateCreated int32 `json:"date_created,omitempty"`
	// Username for the channel
	SmtpUsername string `json:"smtp_username,omitempty"`
}
