/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// InvalidKeyDataErrors error object
type InvalidKeyDataErrors struct {
	// error message
	ErrorField string `json:"error_field,omitempty"`
}
