/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// V4MessagesBodyParts struct for V4MessagesBodyParts
type V4MessagesBodyParts struct {
	// MIME version. By default set to `1.0`
	Version string `json:"version,omitempty"`
	// MIME type. By default set to `plain/text`
	Type string `json:"type,omitempty"`
	// Content character set -- i.e. UTF-8, ISO-8859-1, etc.
	Charset string `json:"charset,omitempty"`
	// Content encoding – i.e. 7bit, quoted-printable, base64, etc. default base64
	Encoding string `json:"encoding,omitempty"`
	// Actual part’s content in its raw form
	Content string `json:"content,omitempty"`
}
