/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// BadRequestSchemaData Data
type BadRequestSchemaData struct {
	// error object
	Errors map[string]interface{} `json:"errors,omitempty"`
}
