/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// StatsResponseDataItems struct for StatsResponseDataItems
type StatsResponseDataItems struct {
	Accepted     int32 `json:"accepted,omitempty"`
	Complained   int32 `json:"complained,omitempty"`
	Delivered    int32 `json:"delivered,omitempty"`
	Clicked      int32 `json:"clicked,omitempty"`
	Opened       int32 `json:"opened,omitempty"`
	Failed       int32 `json:"failed,omitempty"`
	Unsubscribed int32 `json:"unsubscribed,omitempty"`
	Queued       int32 `json:"queued,omitempty"`
}
