/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// SliceValue the model 'SliceValue'
type SliceValue string

// List of sliceValue
const (
	CHANNEL     SliceValue = "channel"
	DOMAIN      SliceValue = "domain"
	RCPT_DOMAIN SliceValue = "rcpt_domain"
	RCPT_ISP    SliceValue = "rcpt_isp"
)
