/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// AccountDataAddress Full address of account owner. See below
type AccountDataAddress struct {
	// Account owner’s street address
	Street string `json:"street,omitempty"`
	// Account owner’s city
	City string `json:"city,omitempty"`
	// Account owner’s state
	State string `json:"state,omitempty"`
	// Account owner’s country
	Country string `json:"country,omitempty"`
}
