/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// GetApiKeysDataItems struct for GetApiKeysDataItems
type GetApiKeysDataItems struct {
	// Current status of the API key
	Status string `json:"status,omitempty"`
	// Description for API key
	Description string `json:"description,omitempty"`
	// The actual API key value
	Key string `json:"key,omitempty"`
	// Timestamp of API key creation
	DateCreated string `json:"date_created,omitempty"`
}
