/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// MessagesResponseDataUnsubsItems struct for MessagesResponseDataUnsubsItems
type MessagesResponseDataUnsubsItems struct {
	// Time when the unsubscribe request was made
	UnsubTime string `json:"unsub_time,omitempty"`
}
