/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// GetCallbackLogsDataItems struct for GetCallbackLogsDataItems
type GetCallbackLogsDataItems struct {
	// HTTP code for the callback
	Code int32 `json:"code,omitempty"`
	// HTTP or AWS SQS response message from the server
	Msg string `json:"msg,omitempty"`
	// Time of callback in RFC 2822 or UNIX epoch format
	Time string `json:"time,omitempty"`
}
