/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// MessagesResponseDataClicksItems struct for MessagesResponseDataClicksItems
type MessagesResponseDataClicksItems struct {
	// Timestamp of when message links were clicked
	ClickTime string `json:"click_time,omitempty"`
	// IP address of where links were clicked
	RemoteIp string `json:"remote_ip,omitempty"`
	// User agent of device on which links were clicked
	Ua string `json:"ua,omitempty"`
}
