/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// V4MessagesRecipients At least one of `to`, `cc`, `bcc` or `bulk_list` must be specified here. `bulk_list` can not be used with `to`, `cc` or `bcc`
type V4MessagesRecipients struct {
	// TO recipients list
	To []V4MessagesRecipientsTo `json:"to,omitempty"`
	// CC recipients list
	Cc []V4MessagesRecipientsTo `json:"cc,omitempty"`
	// BCC recipients list
	Bcc []V4MessagesRecipientsTo `json:"bcc,omitempty"`
	// Distribution list. Instead of an individual email to multiple recipients, multiple emails to multiple recipients will be created.
	BulkList []V4MessagesRecipientsTo `json:"bulk_list,omitempty"`
}
