/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// DurationValue the model 'DurationValue'
type DurationValue string

// List of durationValue
const (
	LAST_HOUR   DurationValue = "last_hour"
	LAST_DAY    DurationValue = "last_day"
	LAST_WEEK   DurationValue = "last_week"
	LAST_MONTH  DurationValue = "last_month"
	THIS_HOUR   DurationValue = "this_hour"
	THIS_DAY    DurationValue = "this_day"
	THIS_WEEK   DurationValue = "this_week"
	THIS_MONTH  DurationValue = "this_month"
	LAST_24HRS  DurationValue = "last_24hrs"
	LAST_7DAYS  DurationValue = "last_7days"
	LAST_30DAYS DurationValue = "last_30days"
	MTD         DurationValue = "mtd"
	TOTAL       DurationValue = "total"
	THIS_YEAR   DurationValue = "this_year"
	YTD         DurationValue = "ytd"
	LAST_YEAR   DurationValue = "last_year"
)
