/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// MessagesResponseDataMsgData struct for MessagesResponseDataMsgData
type MessagesResponseDataMsgData struct {
	// Email address of the recipient
	RcptTo string `json:"rcpt_to,omitempty"`
	// Email address of the sender
	From string `json:"from,omitempty"`
	// Message subject
	Subject string `json:"subject,omitempty"`
}
