/*
 * SMTP Public API overview
 *
 * SMTP.com Public API v4
 *
 * API version: 4.0.0
 * Contact: support@smtp.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package smtp

// V4MessagesBody Array of content parts as defined below
type V4MessagesBody struct {
	Parts       []V4MessagesBodyParts       `json:"parts,omitempty"`
	Attachments []V4MessagesBodyAttachments `json:"attachments,omitempty"`
}
